---
all:
    vars:
      ansible_user: azureuser
      ansible_password: ${{ secrets.PASSWORD_VAULT }}
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    children:
      jenkins:
        hosts:
          "techstarter.ddns.net":
            ansible_host: 13.95.143.27
      server:
        hosts:
          "techstarter2.ddns.net":
            ansible_host: 13.95.143.26
