---
all:
    vars:
      ansible_user: azureuser
      ansible_ssh_private_key_file: ./sshkey
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    children:
      jenkins:
        hosts:
          "techstarter.ddns.net":
            ansible_host: 40.68.6.167
      server:
        hosts:
          "techstarter2.ddns.net":
            ansible_host: 40.68.7.62
