---

- name: Update
  become: true
  hosts: all
  tasks:
    - apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
        autoclean: yes

- name: Install tools
  become: true
  hosts: all
  tasks:
    - apt:
        name:
            - curl
            - nginx
            - docker.io
        state: present

- name: setup server
  become: true
  hosts: server
  tasks:
    - name: Add system user
      user:
        name: "deploy"
        password: '*'
        append: yes
        groups: docker

- name: install java
  become: true
  hosts: jenkins
  vars:
    jenkins_domain_name: techstarter.ddns.net
  tasks:
    - name: Download Long Term Jenkins release
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
    - name: add jenkins key
      shell: |
        echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
        https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
        /etc/apt/sources.list.d/jenkins.list > /dev/null
        
    - name: install pip3
      apt: name=python3-pip state=present  
      
    - name: Install certbot
      pip:
        name:
          - certbot
          - certbot-nginx
        executable: pip3
      tags:
        - nginx
        - certbot

    - name: Register certbot
      shell: |
        certbot -n register --agree-tos --email abdulwahab.shukri@student.techstarter.de
        touch /etc/letsencrypt/.registered
      args:
        creates: /etc/letsencrypt/.registered
      tags:
        - nginx
    
    - name: 'Get certificate'
      command: '/usr/local/bin/certbot -n --nginx certonly -d techstarter.ddns.net'
      args:
        creates: '/etc/letsencrypt/live/techstarter.ddns.net'
      ignore_errors: true
      tags:
        - nginx
        - certbot
        
    - apt:
        update_cache: yes
        autoclean: yes
        name:
            - default-jre
            - default-jdk
            - jenkins
        state: present

    - name: daemon-reload to pick up config changes
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start jenkins
      ansible.builtin.systemd:
        name: jenkins
        state: started
    - ansible.builtin.template:
        src: jenkins.j2
        dest: /etc/nginx/sites-enabled/default
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
